### ISSUE TITLE
Does it work correctly with unfused iterators?

### ISSUE THREAD

**Issue by vi** [birkenfeld/iter-read#1]
I see `next` being called even after it has returned `None`.

This may lead to a memory leak, as my iterator can return `Some`s af infinum after being errornously called again.

If only fused iterators are indeed expected, maybe bound by `std::iter::FusedIterator`?

**Comment by birkenfeld** [comment]
I think you're right - I guess it's better to fix the implementation instead of requiring `fuse`d iterators?

**Comment by vi** [comment]
If the fix does not degrate performance then yes.

**Comment by birkenfeld** [comment]
I didn't manage that, and since one of the main use cases are slice iterators which are intrinsically fused, I'm switching to requiring `FusedIterator` in 0.3.

Thanks for the report!
